export { assertResource } from "./assert.ts"
export { convertResourceFromDescriptor } from "./convert/fromDescriptor.ts"
export { convertResourceToDescriptor } from "./convert/toDescriptor.ts"
export { isRemoteResource } from "./helpers.ts"
export { inferFormat, inferName } from "./infer.ts"
export type { License } from "./License.ts"
export { loadResourceDescriptor } from "./load.ts"
export type { Resource } from "./Resource.ts"
export type { Source } from "./Source.ts"
export { saveResourceDescriptor } from "./save.ts"
export { validateResourceMetadata } from "./validate.ts"
