name: general

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-linux:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - name: Setup Pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Install Dependencies
        run: pnpm install
      - name: Build Packages
        run: pnpm build
      - name: Test Packages
        run: pnpm test
      - name: Upload Coverage
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5
        with:
          use_oidc: true

  test-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - name: Setup Pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Install Dependencies
        run: pnpm install
      - name: Build Packages
        run: pnpm build
      - name: Test Packages
        run: pnpm test

  test-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - name: Setup Pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Install Dependencies
        run: pnpm install
      - name: Build Packages
        run: pnpm build
      - name: Test Packages
        run: pnpm test:win

  release:
    needs: [test-linux, test-macos, test-windows]
    environment: release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/')

    outputs:
      created: ${{ steps.release.outputs.new_release_published }}
      version: ${{ steps.release.outputs.new_release_version }}

    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Install Dependencies
        run: pnpm install
      - name: Release Packages
        uses: cycjimmy/semantic-release-action@ba330626c4750c19d8299de843f05c7aa5574f62 # v5
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
